"""Render docs/DATASET_REPORT.md, docs/EVALUATION.md and docs/LATENCY.md from the computed JSON.

Numbers in these documents are never typed by hand — they are read from
data/processed/dataset_report.json, data/processed/profile_report.json and
data/evaluation/evaluation_results.json.

Usage: python scripts/write_reports.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
PROC = ROOT / "data" / "processed"
EVAL = ROOT / "data" / "evaluation"


def f(v, nd=3):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    return str(v)


def table(rows: list[list], header: list[str]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(f(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


# ====================================================================== dataset
def dataset_report() -> str:
    d = json.loads((PROC / "dataset_report.json").read_text(encoding="utf-8"))
    p = json.loads((PROC / "profile_report.json").read_text(encoding="utf-8"))
    kb = d["knowledge_base"]
    lines = ["# Dataset report", "",
             "_Generated by `scripts/write_reports.py` from `data/processed/dataset_report.json` and "
             "`profile_report.json` — do not edit by hand._", "",
             "## Step 1 — what the attached files actually contain", ""]
    for role, info in p["detected"].items():
        lines.append(f"* **{role}** → `{info['file']}` ({info['reason']})")
    lines += ["", "> **Filename mismatch:** `incidents_text.csv` is the *structured* event log and "
              "`incidents_structured.xlsx` is the *text-rich* file. Sources are detected by content.", ""]
    for role in ("text_rich", "structured"):
        pr = p[role]
        ev = pr["expected_vs_actual"]
        lines += [f"### {role} ({pr['rows']} rows)", "",
                  table([[c["column"], c["dtype"], c["nulls"], c["null_pct"], c["unique"]] for c in pr["columns"]],
                        ["column", "dtype", "nulls", "null %", "unique"]), "",
                  f"* expected and present: {', '.join(ev['expected_and_present']) or '—'}",
                  f"* expected but **missing**: {', '.join(ev['expected_but_missing']) or '—'}",
                  f"* present but not in the prompt's list: {', '.join(ev['present_but_not_expected']) or '—'}", ""]
    j = d["join"]
    lines += ["## Step 3 — merge", "",
              f"Example IDs: text-rich `{j['text_rich_id_example']}`, structured `{j['structured_id_example']}`; "
              f"overlapping IDs: **{j['overlapping_ids']}** → {j['decision']}. Source A feeds text/retrieval "
              "features; Source B feeds outcome / time / relationship features (and, for a stratified sample, "
              "conditioned synthetic text).", "",
              "## Steps 4 / 4B — conditioned synthetic text, enrichment, augmentation", ""]
    orc = d["original_row_count"]
    lines += [table([[k, v] for k, v in orc.items()], ["original rows", "count"]), "",
              f"* Rows modified or deleted: **{d['rows_modified_or_deleted']}**",
              f"* Synthetic / augmented rows in the knowledge base: **{d['augmented_synthetic_rows']['knowledge_base']}** "
              f"({d['augmented_synthetic_rows']['note']})",
              f"* Synthetic evaluation-only rows (novel-incident probes, never indexed): "
              f"**{d['augmented_synthetic_rows']['novel_probes (evaluation-only, not indexed)']}**",
              f"* Knowledge-base incidents: **{kb['incidents']}** ({kb['from_source_A_original_text']} with original text, "
              f"{kb['from_source_B_with_synthetic_text']} real Source B rows with generated text)",
              f"* Text generators: {kb['text_generators']}",
              f"* Text-field ratio in the KB: {kb['text_field_ratio']['original']} original vs "
              f"{kb['text_field_ratio']['synthetic']} synthetic text cells (**{kb['text_field_ratio']['synthetic_pct']}% synthetic**)",
              f"* Note quality seeded: {kb['note_quality']} · seeded / real defects: {kb['seeded_defects']}", "",
              "**Derived columns added** (provenance `derived`): " + ", ".join(d["derived_columns_added"]), "",
              "**Families that received generated text** (rows per family):", "",
              table([[k, v] for k, v in kb["rows_per_family"].items()], ["family (ground-truth scenario)", "rows"]), "",
              "## Real vs derived vs synthetic (cell level, all rows, tracked fields)", "",
              table([[k, v] for k, v in d["cell_proportions_all_rows"].items()], ["provenance", "% of non-missing cells"]), "",
              "### Field-level provenance (all rows)", "",
              table([[fld] + [c[k] for k in ("original", "derived", "synthetic", "missing")]
                     for fld, c in d["field_level_provenance_all_rows"].items()],
                    ["field", "original", "derived", "synthetic", "missing"]), "",
              "## Step 5 — repairs of known corruption", "",
              table([[k, json.dumps(v) if isinstance(v, dict) else v] for k, v in d["data_repairs"].items()],
                    ["repair / check", "value"]), ""]
    return "\n".join(lines)


# ====================================================================== evaluation
def evaluation_report() -> str:
    e = json.loads((EVAL / "evaluation_results.json").read_text(encoding="utf-8"))
    L = ["# Evaluation report", "",
         f"_Generated by `scripts/write_reports.py` from `data/evaluation/evaluation_results.json` "
         f"(run `{e['run_id']}`, {e['created_at'][:19]} UTC, dataset fingerprint `{e['dataset_fingerprint']}`). "
         "Every number below was computed by `scripts/run_evaluation.py`; none is hand-entered._", "",
         f"Query set: {e['query_set']} · generator: {e['query_generator']} · components: embedder "
         f"`{e['components']['embedder']}`, reranker `{e['components']['reranker']}`, LLM available: "
         f"{e['components']['llm']['available']}", "",
         "**Ground truth.** Known queries are LLM rewrites (lay / vague / technical) of held-out KB incidents with "
         "CI names, service names and root-cause wording removed. Relevance comes from the generator's scenario / "
         "strategy labels of the source incident — never from the system under test. The source incident is "
         "excluded from retrieval (leave-one-out). Caveat: most KB text is synthetic (see DATASET_REPORT), so "
         "absolute numbers describe performance on this corpus, not on arbitrary real tickets.", ""]
    r = e["retrieval"]
    L += ["## 1. Retrieval", "", r["relevance"], "",
          table([[c] + [v[m] for m in ("MRR", "P@1", "P@5", "Hit@1", "Hit@5", "nDCG@5", "nDCG@10", "R@10")]
                 for c, v in r["configs"].items()],
                ["configuration", "MRR", "P@1", "P@5", "Hit@1", "Hit@5", "nDCG@5", "nDCG@10", "R@10"]), "",
          f"Bootstrap 95% CIs for the deployed configuration ({r['main_config']}): {r['bootstrap_95ci_main']}", "",
          f"_{r['recall_note']}_", "", "By query style (deployed configuration):", "",
          table([[s] + list(v.values()) for s, v in r["by_query_style"].items()],
                ["style"] + list(next(iter(r["by_query_style"].values())).keys())), ""]
    g = e["rag"]
    L += ["## 2. RAG", "", f"Mode: {g['mode']} · {g['n_queries']} test queries", "",
          table([["context precision@5", g["context_precision@5"]], ["context recall", g["context_recall"]],
                 ["faithfulness", g["faithfulness"]["value"]], ["answer relevancy (embedding)", g["answer_relevancy_embedding"]],
                 ["family accuracy@1", g["family_accuracy@1"]],
                 ["resolution-strategy accuracy@1", g["resolution_strategy_accuracy@1"]]], ["metric", "value"]), "",
          f"* Faithfulness basis: {g['faithfulness']['basis']}",
          f"* RAGAS non-LLM metrics: {g['ragas_non_llm']}",
          f"* RAGAS LLM-judged metrics: {g['ragas_llm_metrics']['status']}", ""]
    for k, v in g["definitions"].items():
        L.append(f"* `{k}`: {v}")
    if g.get("confidence_vs_accuracy"):
        L += ["", "Does the displayed confidence mean something? Strategy accuracy per confidence bucket:", "",
              table([[b, v["n"], v["strategy_accuracy"]] for b, v in g["confidence_vs_accuracy"].items()],
                    ["confidence bucket", "n", "strategy accuracy"])]
    lm = e.get("rag_llm_mode", {})
    L += ["", "### LLM mode (generated synthesis)", ""]
    if lm.get("status") == "computed":
        L += [table([["faithfulness (NLI judge)", lm["faithfulness_nli"]],
                     ["mean entailment probability", lm["mean_entailment_probability"]],
                     ["answer relevancy (embedding)", lm["answer_relevancy_embedding"]],
                     ["validator: all steps grounded", lm["validator_all_grounded_rate"]],
                     ["mean unsupported steps / answer", lm["mean_unsupported_steps"]]], ["metric", "value"]), "",
              f"LLM `{lm['llm']}` on {lm['n']} test queries. Judge: {lm['judge']}."]
    else:
        L.append(lm.get("status", "not run"))
    cls = e["classification"]
    L += ["", "## 3. Classification (text → field, used when structured fields are missing)", "",
          table([[k, v["accuracy"], v["macro_precision"], v["macro_recall"], v["macro_f1"], v["weighted_f1"],
                  v["majority_class_baseline_accuracy"], v["n_test"]] for k, v in cls.items()],
                ["task", "accuracy", "macro P", "macro R", "macro F1", "weighted F1", "majority baseline", "n test"]), "",
          f"_{next(iter(cls.values()))['caveat']}_", ""]
    for k, v in cls.items():
        L += [f"<details><summary>Confusion matrix — {k}</summary>", "",
              table([[lab] + row for lab, row in zip(v["labels"], v["confusion_matrix"])], ["true \\ pred"] + v["labels"]),
              "", "</details>", ""]
    rt = e["resolution_time"]
    L += ["## 4. Resolution-time prediction (real timestamps)", "",
          f"{rt['n_train']} train / {rt['n_test']} test, {rt['split']}; features known at open time: {', '.join(rt['features'])}.", "",
          table([["MAE (hours)", rt["hours"]["MAE"]], ["RMSE (hours)", rt["hours"]["RMSE"]], ["R² (hours)", rt["hours"]["R2"]],
                 ["median absolute error (hours)", rt["hours"]["median_absolute_error"]],
                 ["MAE (log hours)", rt["log_hours"]["MAE"]], ["R² (log hours)", rt["log_hours"]["R2"]],
                 ["baseline: global median MAE (log)", rt["baselines_log_hours"]["global_median_MAE"]],
                 ["baseline: CI-subcategory median MAE (log)", rt["baselines_log_hours"]["ci_subcategory_median_MAE"]],
                 ["P25–P75 interval coverage", rt["p25_p75_interval_coverage"]]], ["metric", "value"]), "",
          "Resolution time in this ITSM export is extremely heavy-tailed (minutes to months); the model beats the "
          "baselines but explains little variance. The UI shows it as a median with a P25–P75 interval, not a promise.", ""]
    fx = e["fix_accuracy"]
    L += ["## 5. Fix-accuracy assessment (real Reopen_Time labels)", "",
          table([[k, fx[k]] for k in ("ROC_AUC", "PR_AUC", "brier", "base_rate", "top_decile_reopen_rate", "top_decile_lift",
                                      "n_train", "n_test")], ["metric", "value"]), ""]
    if e.get("patterns"):
        p = e["patterns"]
        c = p["clustering"]
        L += ["## 6. Pattern Intelligence", "",
              table([[k, c[k]] for k in ("n_clusters", "purity", "inverse_purity", "NMI", "ARI", "pairwise_precision",
                                         "pairwise_recall", "pairwise_f1", "pairs_evaluated", "silhouette_at_selected_k")],
                    ["clustering metric", "value"]), "",
              f"Sampled-pair check: {c['sampled_pairs']}. Ground truth: {p['ground_truth']}.", "",
              "**Ablation — what the enriched fingerprint adds:**", "",
              table([[k, v.get("k_selected"), v["purity"], v["inverse_purity"], v["NMI"], v["ARI"], v["pairwise_f1"]]
                     for k, v in p["ablation"].items()], ["features", "k", "purity", "inverse purity", "NMI", "ARI", "pairwise F1"]), "",
              f"Strategy grouping inside families (vs. generator strategy labels): {p['strategy_grouping']}", "",
              f"Cross-symptom root-cause findings: {len(p['cross_symptom_findings'])} families.", ""]
        for x in p["cross_symptom_findings"][:6]:
            L.append(f"* {x['family_id']}: {x['finding']} — {x['symptoms']}")
        L += ["", "Manual spot validation notes: see `docs/MANUAL_VALIDATION.md`.", ""]
    cc = e["causal_chains"]
    L += ["## 7. Causal chains (tagging spot-check)", "",
          f"{cc['chains_available']} chains built; {cc['chains_withheld_no_timestamps']} withheld because the incident "
          f"has no timestamps (no chain is fabricated). Tag distribution: {cc['tag_distribution']}.", "",
          table([[k, v] for k, v in cc["rule_conformance"].items()], ["rule", "conformance"]), ""]
    n = e["novelty"]
    L += ["## 8. Novel Incident Detection", "",
          f"Threshold on P(known): **{n['threshold_p_known']:.4f}**, chosen on the validation split with the rule "
          f"*{n['validation'].get('selection_rule')}*; reported on the held-out test split.", "",
          table([[name, m["precision"], m["recall"], m["f1"], m["false_novel_rate"], m["false_known_rate"], m["n_known"], m["n_novel"]]
                 for name, m in (("validation", n["validation"]), ("test", n["test"]),
                                 ("baseline (max CE logit), test", n["baseline_single_feature"]["test"]))],
                ["split", "precision", "recall", "F1", "false-novel rate", "false-known rate", "n known", "n novel"]), "",
          f"Model weights (standardised features): {n['weights']}. Test errors: "
          + ("; ".join(f"{x['label']} ({x['style']}) p={x['p_known']}: “{x['query']}”" for x in n["test_errors"]) or "none"), "",
          "_Only ~20 novel probes per split: treat these rates as indicative (a single error moves recall by ~5 points)._", ""]
    t = e["troubleshooting"]
    L += ["## 9. Interactive troubleshooting (simulated engineer, formal attempt records)", "",
          table([[k, t[k]] for k in ("n_sessions", "resolution_rate", "first_step_success_rate", "average_steps_to_resolution",
                                     "escalation_rate", "novel_route_rate", "clarification_rate",
                                     "max_clarifications_in_a_session", "round_cap")], ["metric", "value"]), "",
          f"_{t['simulated_engineer']}_", "",
          table([[s, v["resolution_rate"], v["avg_steps"]] for s, v in t["by_style"].items()], ["query style", "resolution rate", "avg steps"]), ""]
    c = e["correlation"]
    ct = c["test"]
    L += ["## 10. Live correlation", "",
          f"Similarity threshold **{c['selected_similarity_threshold']}** selected by {c['selection']}. Window "
          f"{c['window_minutes']} min, alert at ≥ {c['min_incidents']} tickets. {c['stream_design']}.", "",
          table([["correlation precision", ct["correlation_precision"]], ["false correlation rate", ct["false_correlation_rate"]],
                 ["burst detection recall", ct["burst_detection_recall"]],
                 ["noise-only streams with a false alert", ct["noise_only_false_alert_rate"]],
                 ["detection latency, minutes (mean)", ct["detection_latency_minutes"].get("mean")],
                 ["burst tickets needed to alert (mean)", ct["burst_tickets_needed_to_alert"].get("mean")],
                 ["bursts / alerts (test)", f"{ct['bursts']} / {ct['alerts']}"]], ["metric (test streams)", "value"]), ""]
    ec = e["evidence_chain"]
    L += ["## 11. Evidence Chain completeness", "", ec["definition"], "",
          table([[k, v["n"], v["complete_core_rate"], v["mean_completeness"], v["insufficient_field_counts"]]
                 for k, v in ec.items() if k != "definition"],
                ["queries", "n", "complete core (family + root cause + resolution)", "mean field completeness", "fields marked insufficient"]), "",
          "For NOVEL incidents the chain deliberately reports family / root cause / resolution as insufficient evidence.", ""]
    q = e["quality_manager"]
    L += ["## 12. Knowledge Quality Manager vs. seeded defects", "",
          table([[k, v["seeded"], v["flagged"], v["true_positives"], v["precision"], v["recall"]]
                 for k, v in (("low-quality notes", q["low_quality_notes"]), ("seeded contradictions", q["seeded_contradictions"]))],
                ["defect", "seeded", "flagged", "TP", "precision", "recall"]), "",
          f"Real Source A category/text conflicts flagged: {q['real_source_A_category_conflicts_flagged']} · exact duplicates: "
          f"{q['exact_duplicates_flagged']} · near duplicates: {q['near_duplicates_flagged']} · mean quality by text "
          f"provenance: {q['mean_score_by_text_provenance']}.", "",
          "Contradiction detection is the weakest QM check: a wrong-but-plausible note is hard to separate from a "
          "legitimately different fix without an LLM judge; it is reported as-is.", ""]
    L += ["## 13. Latency", "", "See `docs/LATENCY.md`.", ""]
    return "\n".join(L)


def latency_report() -> str:
    e = json.loads((EVAL / "evaluation_results.json").read_text(encoding="utf-8"))
    lat = e["latency"]
    rows = [[k, v.get("n"), v.get("median"), v.get("p95"), v.get("mean")] for k, v in lat["stages_ms"].items()
            if isinstance(v, dict) and "median" in v]
    notes = [f"* {k}: {v['note']}" for k, v in lat["stages_ms"].items() if isinstance(v, dict) and "note" in v]
    lm = e.get("rag_llm_mode", {})
    llm = lm.get("latency_ms")

    def secs(d: dict) -> str:
        return f"median {d['median'] / 1000:.1f} s, p95 {d['p95'] / 1000:.1f} s (n={d['n']})"

    return "\n".join([
        "# Latency & cost", "",
        f"_Generated from `data/evaluation/evaluation_results.json` (run `{e['run_id']}`). Device: **{lat['device']}**._", "",
        "## Per-stage latency of the analysis pipeline (ms)", "",
        table(rows, ["stage", "n", "median", "p95", "mean"]), "", *notes, "",
        "## LLM stages", "",
        (f"Measured with a local `{lm['llm']}` on the same GPU, live calls only "
         f"({lm.get('llm_live_calls', '?')} calls, {lm.get('llm_cache_hits', '?')} cache hits): "
         f"generation {secs(llm['llm_generation'])}; validation {secs(llm['llm_validation'])}." if llm else
         "LLM stages are skipped in retrieval-only mode (0 ms)."), "",
        "## Trade-offs made", "",
        "* **One incident = one chunk.** ~3k chunks keep BM25 and vector search well under 20 ms each; no chunk "
        "fan-out or result de-fragmentation is needed.",
        "* **Cross-encoder on the top 30 fused candidates only.** Reranking is the most expensive retrieval stage; "
        "30 candidates keep it at tens of ms on a GPU (a few hundred ms on CPU) while the evaluation shows the fused "
        "list already contains the relevant incidents (see Hit@5 of `hybrid_rrf`).",
        "* **Deterministic first, LLM last.** Query translation, fingerprinting, family matching, novelty, ranking, "
        "confidence and the Evidence Chain use no LLM calls. An LLM is used only for (optional) query expansion when "
        "the rules find < 2 concepts, resolution synthesis and validation — at most 3 calls per request.",
        "* **Caching.** LLM responses are cached on disk (`data/processed/llm_cache.jsonl`); models are loaded once "
        "per process; KB additions only rebuild BM25 (sub-second) and upsert one vector.",
        "* **Duplicate collapsing before ranking.** Retrieval runs over canonical records only, so 22 identical tickets "
        "cost one candidate slot instead of 22.",
        "* **Cost.** In retrieval-only mode the marginal cost per request is local compute only. With an API LLM "
        "(e.g. gpt-4o-mini) a full analyze call uses ~1–3 LLM calls of a few hundred tokens each.",
    ])


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    (DOCS / "DATASET_REPORT.md").write_text(dataset_report(), encoding="utf-8")
    if (EVAL / "evaluation_results.json").exists():
        (DOCS / "EVALUATION.md").write_text(evaluation_report(), encoding="utf-8")
        (DOCS / "LATENCY.md").write_text(latency_report(), encoding="utf-8")
    else:
        sys.exit("run scripts/run_evaluation.py first")
    print("reports written to docs/")
